### ISSUE TITLE
Crear milestones para este proyecto.

### ISSUE THREAD

**Issue by AndyApG** [AndyApG/DEV009-md-links#1]
**TAREAS **GENERALES****

- [x]  Fork del repositorio. 
- [x]   Lectura sobre como crear milstones
- [x]  Crear un milston por Hito del readme
- [x]  Agregar los issues correspondientes al Hito1.
- [x]  Clonar el repositorio

**Comment by AndyApG** [comment]
**OAs**

 

- [x] Git: Instalación y configuración
- [x]  Git: Control de versiones con git (init, clone, add, commit, status, push, pull, remote)
- [x]  Git: Integración de cambios entre ramas (branch, checkout, fetch, merge, reset, rebase, tag)
- [x]  GitHub: Creación de cuenta y repos, configuración de llaves SSH
- [x]  GitHub: Colaboración en Github (branches | forks | pull requests | code review | tags)
- [x]  GitHub: Organización en Github (projects | issues | labels | milestones | releases)
