### ISSUE TITLE
Crear la funcion mdLinks

### ISSUE THREAD

**Issue by AndyApG** [AndyApG/DEV009-md-links#4]
- [x] Es una promesa #6 
- [x] Devuelve error si la ruta no existe #8 
- [x]  Si es ingresado un path relativo lo convierte a absoluto #6, #8 
- [x] Verifica la extencion del archivo #13
- [x] #14 
- [x] #15
